//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Version_3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class database_testEntities : DbContext
    {
        public database_testEntities()
            : base("name=database_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
    
        public virtual ObjectResult<displayData_Result> displayData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<displayData_Result>("displayData");
        }
    
        public virtual ObjectResult<displaySortedData_Result> displaySortedData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<displaySortedData_Result>("displaySortedData");
        }
    
        public virtual ObjectResult<displaySortedDataRank_Result> displaySortedDataRank()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<displaySortedDataRank_Result>("displaySortedDataRank");
        }
    }
}
